### ISSUE TITLE
Include shared dependencies

### ISSUE THREAD

**Issue by Ian-MacLeod** [bequest/zygoat#10]
I've tried to list all dependencies we want to include in Zygoat v1 that aren't included in other issues or in Zygoat already. Feel free to add anything that you think is missing. Also, let me know if you think anything on here should not be included.

## Frontend
material-ui
WUI
prop-types
mobx
axios? Do we want to include an API utility file?
sentry

#### Dev dependencies
jest

## Backend
django-anymail (assuming we still want to use this and Mandril)
pytz?
factoryboy
sentry

#### Dev dependencies
pytest (pytest-django, pytest-cov)

**Comment by markrawls** [comment]
> axios? Do we want to include an API utility file?

Up front I wanna keep it simple, I'm thinking just `isomorphic-unfetch` and an `swr` hook.

In addition to that, NextJS has its own API route management that lets you do some cool stuff, and is what we should be using.

https://nextjs.org/docs/api-routes/introduction
https://github.com/zeit/next.js/blob/canary/examples/with-universal-configuration-build-time/next.config.js

**Comment by Ian-MacLeod** [comment]
`isomorphic-unfetch` and `swr` hooks sound good to me. As for the NextJS API route management, it looks like we limited to using their JS server-side framework, which is likely not what we want. Am I missing something there?

Even if we use `isomorphic-unfetch`, there will likely be some logic shared across our frontend apps (e.g. setting `X-Requested-With` and `X-CSRFToken` headers). We could let the apps decide on their own implementation for that stuff, but I thought it might warrant an place in Zygoat.

**Comment by markrawls** [comment]
> As for the NextJS API route management, it looks like we would be limited to using their JS server-side framework, which is likely not what we want. Am I missing something there?

Generally speaking you use those internal API routes to call out to whatever server you're looking for and then pass it on. Using the dynamic API routing we could set a single file generic view that just forwards the request on to the backend and passes on the response, which is what I was thinking of doing here.

 > Even if we use isomorphic-unfetch, there will likely be some logic shared across our frontend apps (e.g. setting X-Requested-With and X-CSRFToken headers). We could let the apps decide on their own implementation for that stuff, but I thought it might warrant an place in Zygoat.

Fair point. I think we should be using that in our generic API route, which should be relatively straightforward. That would disable server side rendering for that page, but honestly I think that's probably fine. Most authenticated pages will not be having that issue.

**Comment by Ian-MacLeod** [comment]
I'm not sure that I see the point of passing requests to the backend through the Next API. It seems like an unnecessary layer of indirection. Why not just send the request to the backend directly?

**Comment by markrawls** [comment]
It's the NextJS equivalent of proxying, basically. We're gonna have to add that hop one way or another now that the frontend isn't being served by the backend, as we want that to be configurable at runtime.

**Comment by Ian-MacLeod** [comment]
Why do we need (or want) it to be configurable at runtime? I guess I don't see what's wrong with just pulling the API url from configuration and sending the request directly to the backend (in all environments).

**Comment by markrawls** [comment]
The backend URL changes for every application between every available environment, and there are two separate ones for dev (one for SSR inside the container, one outside).

We need to pull that from environment variables on the frontend. Running it through a proxy (like most frontend apps nowadays) gives us a few benefits - there's only one backend URL (since all requests are done from inside the container on dev), we don't have to pull the environment variable in for every API function and can just use relative URLs, we can secure the backend stack to require calls to come from within its own security group.

Ultimately though I think we are talking about the same thing? One way or another these requests need to be proxied to a URL that Zygoat does not know, need to know, or have any method of being aware of.
