### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by Ian-MacLeod** [bequest/zygoat#12]
Perhaps we want to run prettier on both frontend and backend moving forward?

**Comment by cviveiro** [comment]
I naively like the idea of running it on both

**Comment by markrawls** [comment]
There's not even a beta plugin available for Python, I'm not sure how you wanna use it on the backend

**Comment by Ian-MacLeod** [comment]
If we want to auto-format python code there are options for that, too. We could consider something like [black](https://github.com/psf/black).
