### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by kborer** [bequest/zygoat#64]
Please add some automated checking to help with accessibility. 

Webalin looks like a good place to start: https://webalin.readthedocs.io/en/latest/

There are over a hundred more listed here: https://www.w3.org/WAI/ER/tools/

**Comment by markrawls** [comment]
We're already using `eslint-plugin-jsx-a11y` which follows a pretty universal standard for accessibility. Do we need anything else?

**Comment by swang192** [comment]
We might need something like [`react-axe`](https://github.com/dequelabs/react-axe).

Haven't looked too deeply into this yet, but according to some light research from [this article](https://web.dev/accessibility-auditing-react/):

> eslint-plugin-jsx-a11y can help you easily pinpoint any accessibility issues in your JSX, but it does not test any of the final HTML output.
